#!/usr/bin/env python
# coding=utf-8

# Group:    Stegasaurus
# Version:  0.01
# Date:     2012-2-17

# ==== Group Members ====
#  - Nick Aldwin <aldwin@ccs.neu.edu>
#  - Gary Katsevman <gkatsev@css.neu.edu>
#  - Alex Metzger <asm@ccs.neu.edu>
#  - Melissa Xie <emzee@ccs.neu.edu>

# ==== Usage ====
# see README

import getopt, sys, random
from audioformat import checkformat, convertmp3
from engine import encode, decode

# Constants
DECODE = "decode"               # Operation mode of the software
ENCODE = "encode"
WAV = "wav"                     # input type
RATE = 44100                    # Sample rate (expected)
SEED = "our cool awesome seed"  # Random number generator seed
# FIXME: Make sure this path reflects the machine you're testing on
# This isn't used anywhere at the moment...
LAMEPATH = "/course/cs4500wc/Lame/src/lame-3.98.4/frontend/lame" # Path to LAME executable

def usage():
    """ Prints program usage and exits """
    print """./stegan --encode file1 file2 file3
./stegan --decode file4 file5
file1 → is input audio file, the carrier
file2 → is input message file
file3 → is output audio file
file4 → is input audio with steganography; i.e., file3
file5 → is output message file"""
    exit()

def main():
    """ Main operations """
    # Attempt to get the options the user provided
    try:
        mode, opts = getopt.getopt(sys.argv[1:],"",[DECODE,ENCODE])
    except:
        # if the command is improperly formed, print the usage
        usage()

    if len(mode) < 1:
        # if the mode isn't there, print the usage
        print "ERROR: No mode specified!"
        usage()

    # get the mode the user indicated
    mode = mode[0][0].strip('-')
    nargs = 3 if mode == ENCODE else 2

    # If the file has an mp3 extension
    if opts[0][-3:] == "mp3":
        # Convert it to wav
        convertmp3(opts[0])
        # change the filename's extension in the options array
        opts[0] = opts[0][:-4]+".wav"

    # check for appropriate number of arguments
    if len(opts) < nargs:
        usage()
    if not checkformat(opts[0], WAV, RATE):
        print "ERROR: File is of unexpected type!"
        usage()

    random.seed(SEED)   # seeds the random generator
    if mode == ENCODE:
        encode(opts) # calls encode on the arguments provided
    else:
        decode(opts) # calls decode on the arguments provided

if __name__ == '__main__':
    main()
